name: Build and Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and test Docker image
        run: |
          docker build . -t my-app
          docker run my-app pytest tests/

      - name: Log in to Heroku
        uses: akhileshns/heroku-deploy@v3.10.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: your-heroku-app-name
          docker_image: my-app
